### PR TITLE
README: document /signal list contacts|groups

### PR DESCRIPTION
**Pull request by Mic92**

### CODE REVIEW

**Comment by Mic92** [comment]
Btw `/signal link` was broken for me i.e. it did not output anything.

weechat-signal logged this on startup

```
2021-01-31 09:28:45     signal  Got unhandled unexpected_error message from signald, see debug log for more info
2021-01-31 09:28:45     signal  Got unhandled unexpected_error message from signald, see debug log for more info
2021-01-31 09:28:45     signal  Got unhandled unexpected_error message from signald, see debug log for more info
2021-01-31 09:28:45     signal  Successfully subscribed to +44**********
2021-01-31 09:28:45     signal  Got unhandled unexpected_error message from signald, see debug log for more info
```

This came from signald 0.11.1:

```
09:28:45.644 [socketlistener] WARN  io.finn.signald.SocketHandler - unable to process request for non-existent account
09:28:45.645 [socketlistener] INFO  manager-***********00 - Creating new manager for ***********00 (stored at /home/joerg/.config/signald)
09:28:45.645 [socketlistener] WARN  io.finn.signald.SocketHandler - unable to process request for non-existent account
09:28:45.646 [socketlistener] INFO  manager-***********00 - Creating new manager for ***********00 (stored at /home/joerg/.config/signald)
09:28:45.646 [socketlistener] WARN  io.finn.signald.SocketHandler - unable to process request for non-existent account
09:28:45.647 [socketlistener] INFO  manager-***********00 - Creating new manager for ***********00 (stored at /home/joerg/.config/signald)
09:28:45.647 [socketlistener] WARN  io.finn.signald.SocketHandler - unable to process request for non-existent account
```

I ended up using netcat on the signald socket.

**Comment by Mic92** [comment]
Mhm. There is no `link` code at all! The readme is out-of-date.

**Comment by Mic92** [comment]
Friendly ping.

**Comment by tych0** [comment]
LGTM, but heads up that this plugin doesn't work with v2 groups or the new signald API, and I don't have the time to update it any more. I've switched to using the desktop client, but would like to switch back at some point if someone else has the time to make things work with the new APIs.

**Comment by Mic92** [comment]
What part for the API has changed apart from groups?

**Comment by tych0** [comment]
signald itself has introduced a versioned API, and this only works with v0.

**Pull request merged**
