### PR TITLE
Hotlist

### PR DESCRIPTION
**Pull request by tych0**
A patch to get the hotlist working, and one to silence some log messages we don't care about.

### CODE REVIEW

**Comment by tych0** [comment]
Ok, I think with all these patches (plus the parallel patch about fixing some more json stuff), the client is pretty functional at this point. Let me know if you have any questions.

**Comment by thefinn93** [comment]
Awesome. I'm not set up to test this, but I'm going to merge this anyway as I have been doing with the last couple PRs. If i give you commit access would you be willing to maintain this thing going forward?

**Comment by tych0** [comment]
Yeah, although probably just the signald branch. Any objection to making that the master branch and closing all the unrelated bugs?

**Comment by thefinn93** [comment]
oh, didn't realize that hasn't been done already. By all means, make it so! 

If you would prefer, you could update this repo's README to point at your fork of it and maintain it under your own name

**Pull request merged**
